name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt update
          sudo apt install gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
          repo sync build/make
          wget -O - https://raw.githubusercontent.com/waydroid/android_vendor_waydroid/lineage-20/manifest_scripts/generate-manifest.sh | bash
          repo sync
          . build/envsetup.sh
          apply-waydroid-patches
          lunch lineage_waydroid_arm64-userdebug
          make systemimage -j$(nproc --all)
          make vendorimage -j$(nproc --all)
