name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 76800
          swap-size-mb: 4096

      - name: Build
        run: |
          sudo apt update
          sudo apt install gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo
          repo init -u https://android.googlesource.com/platform/manifest -b android-security-11.0.0_r67
          repo sync -j16
          rm -rf bootable/recovery
          git clone https://github.com/azwhikaru/twrp_device_rockchip_orangepi-3b.git bootable/recovery
          source build/envsetup.sh
          make clean
          make recoveryimage -j16
